#pragma once

#include "CoreMinimal.h"
#include "NativeGameplayTags.h"

namespace MItemGameplayTags
{
	MASTERPIECE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item);

	MASTERPIECE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Equipment);
	MASTERPIECE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Equipment_Weapon);
	MASTERPIECE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Equipment_Armor);
	MASTERPIECE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Equipment_Accessory);
	MASTERPIECE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Equipment_Special);

	MASTERPIECE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Consumable);
	MASTERPIECE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Consumable_Potion);
	MASTERPIECE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Consumable_Food);
	MASTERPIECE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Consumable_Buff);
	MASTERPIECE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Consumable_Scroll);

	MASTERPIECE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Quest);
	MASTERPIECE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Quest_Main);
	MASTERPIECE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Quest_Side);
	MASTERPIECE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Quest_Event);

	MASTERPIECE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Misc);
	MASTERPIECE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Misc_Material);
	MASTERPIECE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Misc_Currency);
	MASTERPIECE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Misc_Crafting);
	MASTERPIECE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Misc_Key);

	MASTERPIECE_API bool IsItemTag(const FGameplayTag& InItemTag);
	MASTERPIECE_API bool IsEquipmentTag(const FGameplayTag& InItemTag);
	MASTERPIECE_API bool IsConsumableTag(const FGameplayTag& InItemTag);
	MASTERPIECE_API bool IsQuestTag(const FGameplayTag& InItemTag);
	MASTERPIECE_API bool IsMiscTag(const FGameplayTag& InItemTag);
}
